---
language: ruby
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq mcollective
 - ln -s /usr/lib/ruby/1.8/mcollective lib/mcollective
 - ln -s /usr/lib/ruby/1.8/mcollective.rb lib/mcollective.rb
rvm:
  - 1.9.3
  - 2.1.6
matrix:
  allow_failures:
    - rvm: 2.1.6
script: "bundle exec rake spec"
notifications:
  email:
    - infra@timgroup.com

