---
language: ruby
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq mcollective
rvm:
  - 2.1.6
matrix:
  allow_failures:
    - rvm: 2.1.6
script: "bundle exec rake spec"
notifications:
  email:
    - infra@timgroup.com

